
name: CI

on:

  push:
    branches: [ main dev]
  pull_request:
    branches: [ main dev]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build parallel
        run:  cmake -Dparallel = ON
        
      - name: build static
        run: cmake -Dstatic = OFF
