
name: CI

on:

  push:
    branches: [ main dev]
  pull_request:
    branches: [ main dev]



jobs:
  build_consistent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install gtest
        run: sudo apt install libgtest-dev lcov

      - name: build
        run: cmake -B build -Dparallel=false && cd build\ && make

  build_parallel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install gtest
        run: sudo apt install libgtest-dev lcov

      - name: build
        run: cmake -B build -Dparallel=true && cd build\ && make
